version: "3.9"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    tty: true
    stdin_open: true
    restart: always
    volumes:
    - static:/srv/project/static
    ports:
    - 1337:80
    - 443:443
    depends_on:
      - backend

  backend:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 core.wsgi --timeout 60 --log-level debug --max-requests 10000
    container_name: blog-backend
    tty: true
    stdin_open: true
    restart: always
#    ports:
#    - 8000:8000
    volumes:
    - ./:/srv/project
    - static:/srv/project/static
    depends_on:
      - memcache
      - postgres
      - rabbitmq
    env_file:
      - .env

  celery:
    build: .
    container_name: blog-celery
    command: celery -A core worker -l INFO
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
    - ./:/srv/project

  celerybeat:
    build: .
    container_name: blog-celerybeat
    command: celery -A core beat -l INFO
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./:/srv/project

  memcache:
    image: memcached:1.6.9
    container_name: blog-memcache
    tty: true
    stdin_open: true
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: blog-rabbitmq
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .env
    ports:
    - 15672:15672

  postgres:
    image: postgres:12
    container_name: blog-db
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .env
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static:


